# Step 1: Choose the base image
FROM python:3.11

# Step 2: Copy the producer script into the image
COPY producer.sh /producer.sh

# Step 3: Set the working directory
WORKDIR /

# Step 4: Make the script executable
RUN chmod +x /producer.sh

# Step 5: Define the entry point and command to run the script
ENTRYPOINT ["/producer.sh"]